/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Elias (https://sketchfab.com/elias.voet)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gift-box-eb72144b83bf43d98ec1d4fcd979660a
Title: Gift Box
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gift_box.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.6}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials.Pink01}
            position={[0, 1.1, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Pink02}
            position={[0, 1.3, 0]}
            rotation={[0, Math.PI / 2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.Pink02}
            position={[0, 2.2, 0]}
            rotation={[0, -Math.PI / 4, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials.Pink03}
            position={[0, 2.2, 0]}
            rotation={[-0.1, 0, 0]}
            scale={[0.2, 0.4, 0.4]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_12.geometry}
            material={materials.Pink01}
            position={[0, 2.2, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_14.geometry}
            material={materials.Yellow01}
            position={[0, 2.4, 0]}
            scale={0.2}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gift_box.glb')